### ISSUE TITLE
GAE ruby standard environment w/nokogiri broken after some change from google

### ISSUE THREAD

**Issue by sam0x17** [GoogleCloudPlatform/appengine-ruby#31]
Reporting here because in the past this has been the only way to indirectly report an issue to the GAE  ruby standard environment team in lieu of appropriate tags on stackoverflow.

It looks like the ruby GAE standard team changed something in their runtime 1-2 days ago that has broken any new deploys that use nokogiri (which is 90% of ruby apps).

Deploys that were previously working two days ago will now fail when rails tries to run with:
```
Bundler::GemNotFound: Could not find nokogiri-1.10.7 in any of the sources
```

It is impossible to re-produce this error locally for affected projects, and re-installing gems, updating gems, changing ruby versions, etc., seems to have no effect.

I think previously the runtime was including some pre-compiled nokogiri versions, and with this latest change they dropped some of the versions they were previously including, or something. Just a guess.

Would really appreciate it @dazuma if you guys pass this along to the ruby standard environment team.

English stackoverflow issue: [here](https://stackoverflow.com/questions/59292862/sudden-could-not-find-nokogiri-1-10-7-in-any-of-the-sources-error-for-previous)
Japanese stackoverflow issue posted by someone else: [here](https://ja.stackoverflow.com/questions/61330/google-app-engine-standard-%e3%81%ae-ruby-beta-%e3%81%a7%e3%83%87%e3%83%97%e3%83%ad%e3%82%a4%e3%81%8c%e3%81%a7%e3%81%8d%e3%81%aa%e3%81%8f%e3%81%aa%e3%81%a3%e3%81%9f?newreg=c5eb9b0436474e308986530f7177d2d7)

**Comment by dazuma** [comment]
Sam, I've not been able to reproduce this in our internal staging environment. Would you be willing to help with any or all of the following:

* Your full Gemfile and Gemfile.lock
* The build logs for the failed deployment (go to console.cloud.google.com, pull down the menu on the left side and navigate to Cloud Build, find the specific build corresponding to the failed deployment (which you can identify by time), and find the full log.

Would you be willing to post those, or send directly to me at dazuma at google dot com?

**Comment by sam0x17** [comment]
@dazuma logs have been emailed -- thanks again

**Comment by sam0x17** [comment]
Also, here is the app.yaml file (simplified):
```yaml
service: [redacted]-staging
runtime: ruby25
entrypoint: bundle exec rails server Puma -p $PORT
instance_class: F1
handlers:
  - url: /(.*\..*)
    static_files: public/\1
    upload: public/.*\..*
  - url: /.*
    secure: always
    script: auto
env_variables:
  RAILS_ENV: staging
```
